sudo: required

dist: bionic

language: python

python:
    - "3.6"

install:
    - sudo apt-get install -y ffmpeg
    - pip install pandas scipy matplotlib
    - cd gym102919
    - pip install -e '.[atari]'
    - cd ..

jobs:
    include:
        - stage: test
          name: "Unit Tests"
          script:
              - python test.py
